In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Prep for Prep - IFE Summer 2024-submissions (updated 2024-08-01 174018 UTC).csv')

In [3]:
df.head()

,Checkpoint,Lesson,Prompt,Type,Student Name,Student Email,Available Points,Earned Points,Note,Answer 1,Answer 2,Answer 3,Answer 4,Answer 5,Answer 6
0,1 Initiation,1 Orientation,6 Your Why,prompt,Myalei Alexander,malexander.p936@prepforprep.org,3,3.0,NaN,I joined so i can learn how to code,NaN,NaN,NaN,NaN,NaN
1,1 Initiation,1 Orientation,6 Your Why,prompt,Irene Gonzalez,gonzalezfajardo.irene@gmail.com,3,3.0,NaN,to get learn how to code and gain confidence i...,NaN,NaN,NaN,NaN,NaN
2,1 Initiation,1 Orientation,6 Your Why,prompt,madi,madic011009@gmail.com,3,3.0,NaN,i was interested in the business aspect of the...,NaN,NaN,NaN,NaN,NaN
3,1 Initiation,1 Orientation,6 Your Why,prompt,Cannon Jolly,cjolly.pf43@prepforprep.org,3,3.0,NaN,I think that this is a great experience and an...,NaN,NaN,NaN,NaN,NaN
4,1 Initiation,1 Orientation,6 Your Why,prompt,Jordan Gasco,jgasconyc@gmail.com,3,3.0,NaN,I wanted to expand my tech skills in the codin...,NaN,NaN,NaN,NaN,NaN

In [4]:
unique_values = df['Student Name'].unique()
print(unique_values)
mylist=unique_values.tolist()
mylist.sort()
for i in mylist:
    print(i)

['Myalei Alexander' 'Irene Gonzalez' 'madi' 'Cannon Jolly' 'Jordan Gasco'
 'Bailee Timmons27' "Sarah Sookoo '26" 'elmary rodriguez'
 'Marco Andres Rodriguez' 'stephanie o' 'Alexander' 'Michael Oyaniyi'
 'MagentaMovie' 'William Gonzalez' 'Dara Akinwande'
 'Federico Lynch Ferraris' 'aiyana' 'Diana Allado' 'Dawood S'
 'Mahid Shams' 'Joasaphat Valdrz' 'Teferi Richards' 'Arjun Dey' 'Melissa'
 'Mya Lei' 'Ezequiel Martinez' 'Michael Okyere' 'Kayla Garrison'
 'Kevin Xie' 'Erica Guan' 'Nicholas Ramsumair' 'Sofia Mazzella'
 'Zachary Mattis-Thomas' 'Abhishek Chaki' 'Uzochi Onunaku' 'Emilio Bravo'
 'Anthony Rodriguez' 'Mathias Osback' 'Ramatoulaye Bah' 'Casey Mattis'
 'Martina Adogli' 'Alexis Rosario' 'Zinny Ugbala']
Abhishek Chaki
Alexander
Alexis Rosario
Anthony Rodriguez
Arjun Dey
Bailee Timmons27
Cannon Jolly
Casey Mattis
Dara Akinwande
Dawood S
Diana Allado
Emilio Bravo
Erica Guan
Ezequiel Martinez
Federico Lynch Ferraris
Irene Gonzalez
Joasaphat Valdrz
Jordan Gasco
Kayla Garrison
Kevin Xie
MagentaMovie
Mahid Shams
Marco Andres Rodriguez
Martina Adogli
Mathias Osback
Melissa
Michael Okyere
Michael Oyaniyi
Mya Lei
Myalei Alexander
Nicholas Ramsumair
Ramatoulaye Bah
Sarah Sookoo '26
Sofia Mazzella
Teferi Richards
Uzochi Onunaku
William Gonzalez
Zachary Mattis-Thomas
Zinny Ugbala
aiyana
elmary rodriguez
madi
stephanie o

In [5]:
df['Student Name'] = df['Student Name'].replace('zinny', 'Zinny Ugbala')
unique_values = df['Student Name'].unique()
print(unique_values)
df.to_csv('Prep for Prep - IFE Summer 2024-submissions (updated 2024-08-01 174018 UTC).csv', index=False)

['Myalei Alexander' 'Irene Gonzalez' 'madi' 'Cannon Jolly' 'Jordan Gasco'
 'Bailee Timmons27' "Sarah Sookoo '26" 'elmary rodriguez'
 'Marco Andres Rodriguez' 'stephanie o' 'Alexander' 'Michael Oyaniyi'
 'MagentaMovie' 'William Gonzalez' 'Dara Akinwande'
 'Federico Lynch Ferraris' 'aiyana' 'Diana Allado' 'Dawood S'
 'Mahid Shams' 'Joasaphat Valdrz' 'Teferi Richards' 'Arjun Dey' 'Melissa'
 'Mya Lei' 'Ezequiel Martinez' 'Michael Okyere' 'Kayla Garrison'
 'Kevin Xie' 'Erica Guan' 'Nicholas Ramsumair' 'Sofia Mazzella'
 'Zachary Mattis-Thomas' 'Abhishek Chaki' 'Uzochi Onunaku' 'Emilio Bravo'
 'Anthony Rodriguez' 'Mathias Osback' 'Ramatoulaye Bah' 'Casey Mattis'
 'Martina Adogli' 'Alexis Rosario' 'Zinny Ugbala']

In [6]:
df_check=pd.read_csv('Prep for Prep - IFE Summer 2024-submissions (updated 2024-08-01 174018 UTC).csv')
unique_values = df_check['Student Name'].unique()
print(unique_values)

['Myalei Alexander' 'Irene Gonzalez' 'madi' 'Cannon Jolly' 'Jordan Gasco'
 'Bailee Timmons27' "Sarah Sookoo '26" 'elmary rodriguez'
 'Marco Andres Rodriguez' 'stephanie o' 'Alexander' 'Michael Oyaniyi'
 'MagentaMovie' 'William Gonzalez' 'Dara Akinwande'
 'Federico Lynch Ferraris' 'aiyana' 'Diana Allado' 'Dawood S'
 'Mahid Shams' 'Joasaphat Valdrz' 'Teferi Richards' 'Arjun Dey' 'Melissa'
 'Mya Lei' 'Ezequiel Martinez' 'Michael Okyere' 'Kayla Garrison'
 'Kevin Xie' 'Erica Guan' 'Nicholas Ramsumair' 'Sofia Mazzella'
 'Zachary Mattis-Thomas' 'Abhishek Chaki' 'Uzochi Onunaku' 'Emilio Bravo'
 'Anthony Rodriguez' 'Mathias Osback' 'Ramatoulaye Bah' 'Casey Mattis'
 'Martina Adogli' 'Alexis Rosario' 'Zinny Ugbala']

In [7]:
questions=pd.read_csv('incubator_questions_grouped.csv')
questions.head()

,Lesson,Question Name,Question
0,1.1,6 Your Why,['Why did you join this incubator (1 sentence)?']
1,1.1,8 Your Skills Development,['What are the top 3 skills that you want to d...
2,1.1,10 Our Culture,"['Do you have any ground rules, values, or com..."
3,1.1,11 Your Commitment,['Write down a commitment or promise that you ...
4,1.2,10 Who do you Admire?,['Who is a person that you greatly admire?']

In [8]:
print(questions.dtypes)
response_by_student={}
response_by_student = {student: [] for student in mylist}

Lesson           float64
Question Name     object
Question          object
dtype: object

In [9]:

import ast

# Convert only the rows that are strings and look like lists
def to_list_safe(val):
    if isinstance(val, str) and val.startswith("[") and val.endswith("]"):
        try:
            return ast.literal_eval(val)
        except:
            return [val]  # fallback: wrap string in list if it fails
    elif isinstance(val, list):
        return val
    else:
        return [val]  # wrap anything else in a list

# Apply the fix
questions["Question"] = questions["Question"].apply(to_list_safe)

# Check if it's now consistent
print("All entries are lists:", questions["Question"].apply(lambda x: isinstance(x, list)).all())

All entries are lists: True

In [10]:
questions.head(-10)

,Lesson,Question Name,Question
0,1.1,6 Your Why,[Why did you join this incubator (1 sentence)?]
1,1.1,8 Your Skills Development,[What are the top 3 skills that you want to de...
2,1.1,10 Our Culture,"[Do you have any ground rules, values, or comm..."
3,1.1,11 Your Commitment,[Write down a commitment or promise that you w...
4,1.2,10 Who do you Admire?,[Who is a person that you greatly admire?]
5,1.2,13 What interested YOU as our user?,"[What interested YOU as our user?, Did any fea..."
6,1.3,6 YourOnline Community,"[What kind of resources, connections, or value..."
7,1.4,3 Defining Social Innovation,[How would you define social innovation?]
8,1.4,5 Examples of Social Innovation,[Can you think of any examples of social innov...
9,1.4,11 Social Enterprise Prompt,[Think of an idea for an organization that can...
10,1.4,14 Scaling Hero Rats,[What would be required for Hero Rats to reach...
11,1.4,15 Cross-Sectoral Collaboration,[Can you provide an example of a cross-sector ...
12,1.4,20 Social Innovation Ideas,[Have you been inspired to come up a new idea ...
13,1.5,2 Computational Thinking Questions,[Who is better at computational thinking? Huma...
14,1.5,4 Computational Thinking Exercise Questions,[What did you learn today about using computat...
15,1.6,3 What is Entrepreneurship?,[How would you define entrepreneurship?]
16,1.6,5 Questions for Sebastián,[Do you have any questions for Sebastián about...
17,1.6,9 Entrepreneurial Qualities,[What makes Micah an entrepreneur?]
18,1.6,10 Do you think Micah is a social entrepreneur?,[Do you think Micah is a social entrepreneur?]
19,1.6,11 Food Business Idea,[Come up with an idea for a new food or bevera...
20,1.6,17 Envisioning Your Entrepreneurial Life,[What do you think the entrepreneurial experie...
21,1.6,20 Knowledge & Skills Development,[What is the most important thing that you hav...

In [11]:
questions.at[1, "Question"].append("What are the top 3 skills that you want to develop during this incubator experience?")
questions.at[1, "Question"].append("What are the top 3 skills that you want to develop during this incubator experience?")
questions.head()

,Lesson,Question Name,Question
0,1.1,6 Your Why,[Why did you join this incubator (1 sentence)?]
1,1.1,8 Your Skills Development,[What are the top 3 skills that you want to de...
2,1.1,10 Our Culture,"[Do you have any ground rules, values, or comm..."
3,1.1,11 Your Commitment,[Write down a commitment or promise that you w...
4,1.2,10 Who do you Admire?,[Who is a person that you greatly admire?]

In [12]:
# for value in questions["Question Name"]:
#     for i in mylist:
#         row = df[(df["Student Name"] == mylist[i]) & (df[Prompt] == value)]
#         first_row=questions[questions["Question Name"]==value] 
#         list_size=first_row['Questions'].len()
#         j=0
#         for j<=list_size
#             answer="Answer"+" "+(j+1).tostring()
#             response_by_student[mylist[i]].append(row[answer])
#             j+=1
for value in questions["Question Name"]:
    for i in range(len(mylist)):
        student_name = mylist[i] #from list earlier made
        row = df[(df["Student Name"] == student_name) & (df["Prompt"] == value)]  #row where student name and prompt name matc
        
        # row where value in questions df is the Question Name
        first_row = questions[questions["Question Name"] == value]
        list_size = len(first_row.iloc[0]["Question"])  # gets amount of questions for that prompt from list size
        if row.empty:
            # If no match, append 'N/A' for each question in the prompt
            response_by_student[student_name].extend(["N/A"] * list_size)
            continue
        for j in range(list_size):
            answer_col = f"Answer {j + 1}" #makes Answer 1, Answer 2... based on list size         
            if answer_col in row.columns:
                # get the answer from that col and row
                answer_val = row.iloc[0][answer_col]
                response_by_student[student_name].append(answer_val) #add to dictionary from before
            else:
                response_by_student[student_name].append("N/A")  #  if missing write N/A
print("Done!")

Done!

In [18]:
print(response_by_student["Myalei Alexander"])

['I joined so i can learn how to code', 'Good teamwork', 'Empathy', 'And communication', 'Yes to respect everyone’s thoughts and ideas', 'That i will pay attention in coding and get and internship at google', 'I admire my mom', 'Yes the lesson checkpoints', nan, nan, 'Keeping the chat appropriate and school based ', 'N/A', 'The cotton gin ', 'The trash compactor keeps the streets clean and make its easier on santantion workers', 'To expand', 'N/A', 'N/A', 'N/A', 'N/A', 'Humans because we program the computers and tell them what to do', 'That’s i need to explain my ideas throughly to others ', 'To listen to everyone and that we all build offf one another ', 'A business run by someone who is solving a social problem', 'N/A', 'He started his own business ', 'N/A', 'Hot fires with out the mssg', 'Expensive but you make six figures later on down the lin e ', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']

In [13]:
list_of_qs=[]
for value in questions['Question']:
    list_of_qs=list_of_qs+value
print(list_of_qs)

['Why did you join this incubator (1 sentence)?', 'What are the top 3 skills that you want to develop during this incubator experience?', 'What are the top 3 skills that you want to develop during this incubator experience?', 'What are the top 3 skills that you want to develop during this incubator experience?', 'Do you have any ground rules, values, or community norms that you would like to be upheld in our incubator space?', 'Write down a commitment or promise that you want to make to yourself and your future startup team.', 'Who is a person that you greatly admire?', 'What interested YOU as our user?', 'Did any features of the Journey platform seem interesting, or cool, or useful to you as a learner or entrepreneur?', 'Are you motivated by personal entrepreneurial skills development, earning Gemstones, or receiving mentorship?', 'What kind of resources, connections, or value would you like to get out of your online community?', 'How would you define social innovation?', 'Can you think of any examples of social innovation that you have seen in the world?', 'Think of an idea for an organization that can make money and profits, while making social or environmental impact.', 'What would be required for Hero Rats to reach conflict areas all over the world?', 'Can you provide an example of a cross-sector collaboration that created social change?', 'Have you been inspired to come up a new idea for a social innovation or a social venture?', 'If so, please describe.', '', 'Who is better at computational thinking? Humans or Computers? Explain your answer.', 'What did you learn today about using computational thinking to solve a problem?', 'What did you learn today about working on a team?', 'How would you define entrepreneurship?', 'Do you have any questions for Sebastián about starting Cambio Coffee or Cambio Labs?', 'What makes Micah an entrepreneur?', 'Do you think Micah is a social entrepreneur?', 'Come up with an idea for a new food or beverage business that makes a positive impact.', 'What do you think the entrepreneurial experience and lifestyle is like?', 'What is the most important thing that you have learned so far?', 'What makes life difficult for people?', 'How might we make a product or service that addresses someone’s pain?', "What was Daniel's first business?", 'Do you think it would be as easy for Daniel to start his business today?', 'What are some problems you could work on solving?', 'What are the top 3 SDGs that you feel most passionate about tackling?', 'Write a clear problem statement that your business idea will address.', 'What do you hope to gain on your entrepreneurial journey?', 'What do you hope to gain on your entrepreneurial journey?', "Do you think you've developed any new mindsets or skills?"]

In [14]:
import csv
import json  

csv_filename = 'first_checkpoint_responses.csv'

with open(csv_filename, 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)

    writer.writerow(['Student Name', 'Responses'])

    for key, value in response_by_student.items():
        writer.writerow([key, json.dumps(value)])  # serialize list as a JSON string

print(f"CSV file '{csv_filename}' created successfully.")

CSV file 'first_checkpoint_responses.csv' created successfully.

In [15]:
import pandas as pd
import json

first = pd.read_csv("first_checkpoint_responses.csv")
first["Responses"] = first["Responses"].apply(json.loads)  # convert string back to list

In [16]:
first.head()

        Student Name                                          Responses
0     Abhishek Chaki  [I joined because I do IFE, Public Speaking, C...
1          Alexander  [I want to be able to learn how to make a busi...
2     Alexis Rosario  [N/A, N/A, N/A, N/A, N/A, N/A, N/A, N/A, N/A, ...
3  Anthony Rodriguez  [N/A, N/A, N/A, N/A, N/A, N/A, My mom, I am in...
4          Arjun Dey  [I joined this incubator to have fun and learn...

In [17]:
first.to_csv("first_checkpoint_responses.csv", index=False)